import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Context from './context';

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
});
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    params: { session, ...params },
}: Readonly<{
    children: React.ReactNode;
    params: { session: any };
}>) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Context session={session}>{children}</Context>
            </body>
        </html>
    );
}
